# NumPy basics

In [2]:
import numpy as np

Create numpy array

In [3]:
x = [10,15,20,30,100,5]
array = np.array(x)
array

array([ 10,  15,  20,  30, 100,   5])

In [4]:
print(f"Size: {array.size} - amount of elements")
print(f"Shape: {array.shape} - rows x column")
print(f"Dimensions: {array.ndim} - amount of axis (1d, 2d, 3d etc...)")
print(f"Data type: {array.dtype} - all elements must be of the same type, there are no mixed types like in python lists")

Size: 6 - amount of elements
Shape: (6,) - rows x column
Dimensions: 1 - amount of axis (1d, 2d, 3d etc...)
Data type: int32 - all elements must be of the same type, there are no mixed types like in python lists


Create 2D array

In [5]:
# create 2 dimensional (2d) array, shape 2x5, with data types of int32, total size is 10 (2x5)
array_2d = np.array((range(5),range(5)))
array_2d

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

In [6]:
print(f"Size: {array_2d.size}")
print(f"Shape: {array_2d.shape}")
print(f"Dimensions: {array_2d.ndim}")
print(f"Data type: {array_2d.dtype}")

Size: 10
Shape: (2, 5)
Dimensions: 2
Data type: int32


Array of strings and its actuall type

In [7]:
array_str = np.array(["Hello","World"])
print(f"Data type: {array_str.dtype} - 'U' - Unicode, '5' max length of a string")

Data type: <U5 - 'U' - Unicode, '5' max length of a string


In [8]:
array_str[0] = "A"
array_str

array(['A', 'World'], dtype='<U5')

In [9]:
array_str[0] = "123456"
array_str

array(['12345', 'World'], dtype='<U5')

Transpose matrix

In [10]:
array_2d.T

array([[0, 0],
       [1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

When element is shorter than given max length of the string, then amount of memory for storing that string is like for w max length anyways.
When element is longer then the string is truncated - not visually, it is loss of information


Course assignment: Array basics

In [11]:
my_list = [x*10 for x in range(1,11)]
my_array = np.array(my_list)
my_array

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [12]:
print(f"Size: {my_array.size}")
print(f"Shape: {my_array.shape}")
print(f"Dimensions: {my_array.ndim}")
print(f"Data type: {my_array.dtype}")

Size: 10
Shape: (10,)
Dimensions: 1
Data type: int32
