# NumPy array more about array creation

In [2]:
import numpy as np

### Ones
Generate array of "1" numbers of speciifed shape

In [4]:
np.ones((1,10))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [6]:
np.ones((2,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [13]:
np.ones((10,1))

array([[1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.]])

In [16]:
np.ones((10,))

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [18]:
np.ones((3,3,3))

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [20]:
np.ones(3,dtype="U1")

array(['1', '1', '1'], dtype='<U1')

### Zeros
Generate array of "0" numbers of speciifed shape

In [22]:
np.zeros((2,5,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

### Arange
Generate numbers from "n" to "z" [n,z), with chosen step between numbers

In [23]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
np.arange(1,100,20)

array([ 1, 21, 41, 61, 81])

In [28]:
np.arange(0,1,0.25)

array([0.  , 0.25, 0.5 , 0.75])

### Linspace
Generate numbers from "n" to "z" [n,z], with chosen amount of numbers you want to get - equal intervals between numbers will be calculated

In [30]:
np.linspace(10,100,10)

array([ 10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

In [32]:
np.linspace(0.3,3,3)

array([0.3 , 1.65, 3.  ])

### Reshape
Reshape the dimensions (aka rows x cols for 2D) of array, the reshape value (row,column) needs to be compatible with current array's shape

In [37]:
np.arange(1,101,1).reshape(10,10)

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [38]:
zeros_4_5 = np.zeros((4,5))
zeros_4_5

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [40]:
zeros_4_5.reshape(2,10)

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [44]:
zeros_4_5.reshape(5,4).shape == zeros_4_5.T.shape

True

NumPy "random" module

In [86]:
# set default seed, "consistent randomness"
rnd = np.random.default_rng(1)

In [89]:
# 10 random floats < 1
rnd.random(10)

array([0.75036467, 0.28040876, 0.48519097, 0.9807372 , 0.96165719,
       0.72478994, 0.54122686, 0.2768912 , 0.16065201, 0.96992541])

In [91]:
# 10 random integers from 1 to one milion
rnd.integers(1,1_000_000,10)

array([772789, 917297, 427313,  39593, 718527, 528589, 872095, 459336,
       368079,  62350], dtype=int64)

In [98]:
# normal distribution, mean = 100, std = 10, n_elements = 10
rnd.normal(100,10,10)

array([103.32813613,  93.48718988, 108.62444796,  98.74407916,
       106.69153241, 112.18843605, 103.82929583,  91.24278857,
        84.85681368, 117.53384118])

Course assignment: array creation

In [100]:
my_array = np.linspace(10,100,10)
my_array.reshape(5,2)

array([[ 10.,  20.],
       [ 30.,  40.],
       [ 50.,  60.],
       [ 70.,  80.],
       [ 90., 100.]])

In [105]:
np.random.random(9).reshape(3,3)

array([[0.41919451, 0.6852195 , 0.20445225],
       [0.87811744, 0.02738759, 0.67046751],
       [0.4173048 , 0.55868983, 0.14038694]])