# NumPy array operations

In [1]:
import numpy as np

In [3]:
array = np.array([
    [1,2,3,4,5,6],
    [2,3,2,3,2,3]
])

x = array[0]
y = array[1]

In [11]:
print("x: ",x, end=" --- ")
print("y: ",y)

x:  [1 2 3 4 5 6] --- y:  [2 3 2 3 2 3]


In [13]:
# array by array multiply -> A1*B1, A2*B2 etc...
x*y

array([ 2,  6,  6, 12, 10, 18])

In [15]:
# arrays need to be same length
x[:,:-1]*y

IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

Broadcasting

In [22]:
# get only half of y array
temp_y = y[:len(y)//2]
temp_y

array([2, 3, 2])

In [24]:
# reshape x, so each row is same length as temp_y
temp_x = x.reshape(2,3)
temp_x

array([[1, 2, 3],
       [4, 5, 6]])

In [26]:
# numpy will be able to apply the vectorization despite shapes not being equal, because it will treat each element of temp_x and unique array
temp_x+temp_y

array([[3, 5, 5],
       [6, 8, 8]])

In [28]:
temp_x*temp_y

array([[ 2,  6,  6],
       [ 8, 15, 12]])

In [29]:
x*100

array([100, 200, 300, 400, 500, 600])

In [30]:
x-200

array([-199, -198, -197, -196, -195, -194])

In [32]:
r = np.random.rand(10)
r

array([0.40993631, 0.5787516 , 0.89105885, 0.54700041, 0.64470693,
       0.4572792 , 0.19745054, 0.46955405, 0.47664605, 0.96005667])

In [35]:
(r*100).round(2)

array([40.99, 57.88, 89.11, 54.7 , 64.47, 45.73, 19.75, 46.96, 47.66,
       96.01])

Course assignment: array operations

In [36]:
prices = (np.random.rand(6)*100).round(2)
prices

array([82.22, 39.5 , 92.92, 28.81, 50.42,  2.91])

In [37]:
prices += 5

In [41]:
discount_percent = np.random.rand(6)

In [43]:
percent_owed = 1-discount_percent

In [51]:
final_owed = (prices*percent_owed).round(2)
final_owed.astype("float64")

array([5.933e+01, 3.224e+01, 4.580e+01, 1.679e+01, 2.290e+00, 1.000e-02])

Filtering arrays

In [100]:
array = np.random.randint(1,101,25)
array

array([94, 36,  5, 58,  8,  1, 88, 56, 91,  7, 36, 75,  6, 20, 87, 19, 18,
       75, 25, 12, 95, 15, 17, 74, 15])

In [101]:
array > 50

array([ True, False, False,  True, False, False,  True,  True,  True,
       False, False,  True, False, False,  True, False, False,  True,
       False, False,  True, False, False,  True, False])

In [102]:
array[array > 50]

array([94, 58, 88, 56, 91, 75, 87, 75, 95, 74])

In [103]:
mask = (array > 50) & (array < 90)
array = array.astype("U12")

In [106]:
array[mask] = "in between"

In [111]:
array

array(['94', '36', '5', 'in between', '8', '1', 'in between',
       'in between', '91', '7', '36', 'in between', '6', '20',
       'in between', '19', '18', 'in between', '25', '12', '95', '15',
       '17', 'in between', '15'], dtype='<U12')

Where

In [112]:
array = np.array([0,11,0,20,2,5,6,0])



In [114]:
np.where(array > 0, "In stock", "Out of sotck")

array(['Out of sotck', 'In stock', 'Out of sotck', 'In stock', 'In stock',
       'In stock', 'In stock', 'Out of sotck'], dtype='<U12')

In [118]:
mapping_array = array*100

In [120]:
np.where(array,mapping_array,"Out of stock")

array(['Out of stock', '1100', 'Out of stock', '2000', '200', '500',
       '600', 'Out of stock'], dtype='<U12')

In [122]:
#array([ 0, 11,  0, 20,  2,  5,  6,  0])
np.where(array % 2 == 0,"even",np.where(array == 11,"accepted",array))

array(['even', 'accepted', 'even', 'even', 'even', '5', 'even', 'even'],
      dtype='<U11')

Course assignment: filtering arrays