# NumPy array indexing and slicing

In [1]:
import numpy as np

In [4]:
array = np.arange(1,16,1).reshape(3,5)
array

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [7]:
array[1]

array([ 6,  7,  8,  9, 10])

In [9]:
array[:2]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [11]:
array[:2,:3]

array([[1, 2, 3],
       [6, 7, 8]])

In [12]:
array[[0,1]]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [14]:
array[:,[2,4]]

array([[ 3,  5],
       [ 8, 10],
       [13, 15]])

In [30]:
# array([[ 1,  2,  3,  4,  5],
#        [ 6,  7,  8,  9, 10],
#        [11, 12, 13, 14, 15]])
array[0::2,1::2]

array([[ 2,  4],
       [12, 14]])

In [18]:
array[[0,1],[2,4]]

array([ 3, 10])

It retruned indexing like (0,2) and (1,4) coordinates, rather than 2 and 4 index cols from 0 and 1 rows

In [21]:
array[[(1,1),(2,2)]]

array([[[ 6,  7,  8,  9, 10],
        [ 6,  7,  8,  9, 10]],

       [[11, 12, 13, 14, 15],
        [11, 12, 13, 14, 15]]])

This is advanced indexing, strange things happen here

Course assignment: array acces

In [31]:
my_array = np.random.rand(9).reshape(3,3)
my_array

array([[0.25785018, 0.67412804, 0.53853518],
       [0.36041001, 0.91412967, 0.81723784],
       [0.20201058, 0.96959766, 0.88689188]])

In [32]:
my_array[:2]

array([[0.25785018, 0.67412804, 0.53853518],
       [0.36041001, 0.91412967, 0.81723784]])

In [33]:
my_array[:,0]

array([0.25785018, 0.36041001, 0.20201058])

In [35]:
my_array[2,1]

0.969597664992324

In [37]:
my_array[0,:]

array([0.25785018, 0.67412804, 0.53853518])